# Generated by Django 3.0 on 2022-05-11 02:02

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PortfoliosAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
