# Generated by Django 3.0 on 2022-05-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfoliosAPP', '0003_auto_20220510_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
