# Generated by Django 3.0 on 2022-05-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfoliosAPP', '0004_auto_20220510_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.ImageField(upload_to='PortfoliosAPP/images/'),
        ),
    ]
