# Generated by Django 3.0 on 2022-05-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfoliosAPP', '0006_project_technologie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.FileField(upload_to='PortfoliosAPP/images/'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
